#!/bin/sh

set -e

lb config noauto \
	--apt-recommends false \
	--cache-packages false \
	--mode "ubuntu" \
	--distribution "jammy" \
	--mirror-binary "http://ubuntu.com" \
	--mirror-bootstrap "http://ubuntu.com" \
	--archive-areas "main contrib non-free non-free-firmware" \
	--image-name "bladeOS-live-indev" \
	--iso-application "bladeOS" \
	--iso-publisher "blade GNU/Linux" \
	--iso-volume "bladeOS indev" \
	--bootloaders "grub-pc grub-efi" \
	--bootappend-live "boot=live components quiet username=bladeos hostname=live-bladeos" \
	"${@}"
